### ISSUE TITLE
TypeError: issue.labels is not iterable

### ISSUE THREAD

**Issue by BasicWolf** [jk1z/gitlab-release-note-generator#11]
Hello, 

We are occasionally getting the following error: `TypeError: issue.labels is not iterable`. It's rather tricky, since the API returns an empty list for issues which have no labels, so iteration should not be a problem. 

Do you by chance know what could cause this?

**Comment by jk1z** [comment]
I will be release a patch tomorrow to hopefully fix this

**Comment by BasicWolf** [comment]
Thank you!

**Comment by jk1z** [comment]
Please try 00freezy00/gitlab-release-note-generator:1.2.5 image

**Comment by BasicWolf** [comment]
Thank you very much! Works like a charm!

**Comment by jk1z** [comment]
No worries 😉
