### ISSUE TITLE
Add option to ignore prereleases?

### ISSUE THREAD

**Issue by rohit-gohri** [jk1z/gitlab-release-note-generator#28]
I use prerelease tags when I deploy to stage, and normal tags when deploying to production.
In my releases I only want the normal tags to be there, and the changelog should also consider the last normal tag and ignore any prerelease tags.

Eg.
- release v1.0.0
- prerelease v1.1.0-0 (ignored)
- prerelease v1.1.0-1 (ignored)
- release v1.1.0

And changelog should generated should be b/w v1.0.0 and v1.1.0

**Comment by jk1z** [comment]
I think you can use TAG_REGEX to filter it out? Something like this would work `/^[0-9]+.[0-9]+.[0-9]+$/`

**Comment by rohit-gohri** [comment]
I guess that would work, I'm no longer actively using gitlab and can't test it out so I'll close this issue.

**Comment by jk1z** [comment]
@rohit-gohri I feel you man. The reason I stopped updating this repo is because I have moved of gitlab as well. Gitlab is just too unstable..We experienced major outage when we were using it almost every 2-3 months

**Comment by rohit-gohri** [comment]
@jk1z That's sad to hear. For me it was because I changed my job
