### ISSUE TITLE
Add opportunity to override gitlab url to private

### ISSUE THREAD

**Issue by Jasstkn** [jk1z/gitlab-release-note-generator#7]
Hi. I would like to use your tool in private gitlab instance. Could you add variable for configure it in docker run command?

**Comment by Jasstkn** [comment]
I've checked source code and found variable **GITLAB_API_ENDPOINT**.

**Comment by jk1z** [comment]
Hi Jasstkn,
Thanks for trying out my tool 😋. Let me know how it goes. Happy to answer any questions.

**Comment by Jasstkn** [comment]
@jk1z it works great! But I'm trying to understand it there a way to create tag from the latest commit in defined branch (develop/master) and generate release notes from previous one.

**Comment by jk1z** [comment]
Assuming you are using `npm version bump`. What I usually do is having a `tag-after-deployment`  job (see example in the reference project) in the CI which it will kick in after the version bump commit regardless of people pushed the tag or not. Then the 
`generate-release-note` job (see example in the reference project) in the CI will trigger upon tag creation to generate the release-note on that tag

**Comment by jk1z** [comment]
Oh don't forget to use `-e TARGET_TAG_REGEX` to distinguish between develop release and production release. For development release regex I would use `^[0-9]+.[0-9]+.[0-9]+(-[0-9]+)$` (e.g. 1.12.0-1), for production release regex I would use `^[0-9]+.[0-9]+.[0-9]+$`

**Comment by Jasstkn** [comment]
I'm using dockerized version of your tool. So, apparently I need to implement this as part of GitlabCI.

**Comment by jk1z** [comment]
> I'm using dockerized version of your tool. So, apparently I need to implement this as part of GitlabCI.

It can be done locally as well, the step ^ is just to automate the process. To run the dockerized version of the tool.

**Comment by jk1z** [comment]
> I'm using dockerized version of your tool. So, apparently I need to implement this as part of GitlabCI.

It can be done locally as well, the steps ^ is just to automate the process. To run the dockerized version of the tool.

1. npm version prerelease (assuming you are releasing on develop) <-- that commits a commit and a tag locally
2. Push the commit and tag to the origin.
3. Run the dockerized version of the tool

**Comment by Jasstkn** [comment]
@jk1z Got it and I'm almost done with gitlabCI. Do you have an example of Release Notes with using labels which you mentioned in README? I didn't find it in your gitlab example. I'm interested in customise Release Notes with sections.
